### ISSUE TITLE
PID_CGROUP_FOLDER vs CGROUP_FOLDER

### ISSUE THREAD

**Issue by vsoch** [cesarvr/container#2]
heyo @cesarvr another question for you! You make a constant called `CGROUP_FOLDER` but then in the function reference `PID_CGROUP_FOLDER` - should the second be the first, or is `PID_CGROUP_FOLDER` from a system include? E.g., here is one of the sections:

```cpp
#include <sys/stat.h>
#include <sys/types.h>
#define CGROUP_FOLDER "/sys/fs/cgroup/pids/container/"

void limitProcessCreation() {
  // create a folder
  mkdir( PID_CGROUP_FOLDER, S_IRUSR | S_IWUSR);  

}
```

**Comment by cesarvr** [comment]
Hi @vsoch , 

Sorry for the late response. There is a mistake there, I should have used ```CGROUP_FOLDER``` instead of ```PID_CGROUP_FOLDER```: 

```cpp
#include <sys/stat.h>
#include <sys/types.h>
#define CGROUP_FOLDER "/sys/fs/cgroup/pids/container/"

void limitProcessCreation() {
  // create a folder
  mkdir( CGROUP_FOLDER, S_IRUSR | S_IWUSR);  

}
```
**First parameter:** is a string, with the name of the folder. 
**Second parameter:** [S_IRUSR | S_IWUSR](http://www.gnu.org/software/libc/manual/html_node/Permission-Bits.html) access level/permissions for the folder.

Cheers.

**Comment by vsoch** [comment]
Awesome, thank you :)
